"use client";

import { useState } from "react";
import { useAccount } from "wagmi";
import { useCreateReferralCode } from "~~/hooks/referral/useReferralActions";
import {
  validateReferralCode,
  generateCodeFromAddress,
  suggestCodes,
} from "~~/services/referral/code-generator";

interface CreateCodeModalProps {
  onClose: () => void;
  onSuccess: () => void;
}

export function CreateCodeModal({ onClose, onSuccess }: CreateCodeModalProps) {
  const { address } = useAccount();
  const { createCode, isCreating } = useCreateReferralCode();

  const [customCode, setCustomCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [suggestions, setSuggestions] = useState<string[]>([]);

  const autoGeneratedCode = address ? generateCodeFromAddress(address) : "";

  const handleCustomCodeChange = (value: string) => {
    const upperValue = value.toUpperCase().replace(/[^A-Z0-9]/g, "");
    setCustomCode(upperValue);
    setError(null);

    if (upperValue.length >= 4) {
      const validation = validateReferralCode(upperValue);
      if (!validation.valid) {
        setError(validation.error || null);
      }
    }
  };

  const handleGenerateSuggestions = () => {
    if (customCode.length > 0) {
      const generated = suggestCodes(customCode);
      setSuggestions(generated);
    }
  };

  const handleCreateCode = async (code: string) => {
    const validation = validateReferralCode(code);
    if (!validation.valid) {
      setError(validation.error || "Invalid code");
      return;
    }

    try {
      await createCode(code);
      onSuccess();
    } catch (err: any) {
      if (err?.message?.includes("Code already taken")) {
        setError("This code is already taken. Try another one.");
      } else if (err?.message?.includes("Already has code")) {
        setError("You already have a referral code.");
      } else {
        setError("Failed to create code. Please try again.");
      }
    }
  };

  return (
    <div className="modal modal-open">
      <div className="modal-box max-w-2xl">
        <h3 className="font-bold text-2xl mb-4">Create Your Referral Code</h3>

        {/* Auto-Generated Option */}
        <div className="mb-6">
          <div className="bg-gradient-to-r from-blue-50 to-purple-50 p-6 rounded-lg border-2 border-blue-200">
            <p className="font-semibold mb-3">✨ Quick Start (Recommended)</p>
            <p className="text-sm text-gray-600 mb-4">
              We've generated a unique code based on your wallet address:
            </p>
            <div className="flex items-center gap-3 mb-4">
              <div className="bg-white px-4 py-3 rounded-lg flex-1">
                <span className="text-2xl font-mono font-bold tracking-wider">{autoGeneratedCode}</span>
              </div>
            </div>
            <button
              onClick={() => handleCreateCode(autoGeneratedCode)}
              disabled={isCreating}
              className="btn btn-primary w-full"
            >
              {isCreating ? (
                <>
                  <span className="loading loading-spinner loading-sm"></span>
                  Creating...
                </>
              ) : (
                "Use This Code"
              )}
            </button>
          </div>
        </div>

        {/* Divider */}
        <div className="divider">OR</div>

        {/* Custom Code Option */}
        <div>
          <p className="font-semibold mb-3">🎨 Create Custom Code</p>
          <p className="text-sm text-gray-600 mb-4">
            Choose your own memorable code (4-12 characters, letters and numbers only)
          </p>

          <div className="form-control mb-4">
            <label className="label">
              <span className="label-text">Custom Code</span>
            </label>
            <input
              type="text"
              placeholder="MYCODE123"
              value={customCode}
              onChange={e => handleCustomCodeChange(e.target.value)}
              className={`input input-bordered w-full ${error ? "input-error" : ""}`}
              maxLength={12}
            />
            {error && (
              <label className="label">
                <span className="label-text-alt text-error">{error}</span>
              </label>
            )}
            <label className="label">
              <span className="label-text-alt">{customCode.length}/12 characters</span>
            </label>
          </div>

          <div className="flex gap-2 mb-4">
            <button
              onClick={() => handleCreateCode(customCode)}
              disabled={isCreating || !customCode || customCode.length < 4 || !!error}
              className="btn btn-primary flex-1"
            >
              {isCreating ? (
                <>
                  <span className="loading loading-spinner loading-sm"></span>
                  Creating...
                </>
              ) : (
                "Create Custom Code"
              )}
            </button>
            <button onClick={handleGenerateSuggestions} className="btn btn-outline">
              Suggest Codes
            </button>
          </div>

          {/* Suggestions */}
          {suggestions.length > 0 && (
            <div className="bg-gray-50 p-4 rounded-lg">
              <p className="text-sm font-semibold mb-3">Suggested Codes:</p>
              <div className="grid grid-cols-2 gap-2">
                {suggestions.map((suggestion, index) => (
                  <button
                    key={index}
                    onClick={() => setCustomCode(suggestion)}
                    className="btn btn-sm btn-outline"
                  >
                    {suggestion}
                  </button>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Requirements */}
        <div className="bg-blue-50 p-4 rounded-lg mt-6">
          <p className="text-sm font-semibold mb-2">Code Requirements:</p>
          <ul className="text-sm text-gray-600 space-y-1">
            <li>✓ 4-12 characters long</li>
            <li>✓ Letters (A-Z) and numbers (2-9) only</li>
            <li>✓ Cannot contain O, 0, I, or 1 (to avoid confusion)</li>
            <li>✓ Must be unique (not already taken)</li>
          </ul>
        </div>

        {/* Close Button */}
        <div className="modal-action">
          <button onClick={onClose} className="btn btn-ghost">
            Cancel
          </button>
        </div>
      </div>
      <div className="modal-backdrop" onClick={onClose}></div>
    </div>
  );
}
