"use client";

import { Address } from "viem";

interface VRFProofProps {
  requestId?: bigint;
  randomSeed?: bigint;
  fulfilled: boolean;
  shuffled: boolean;
  payoutQueue?: Address[];
}

export function VRFProof({ requestId, randomSeed, fulfilled, shuffled, payoutQueue }: VRFProofProps) {
  if (!shuffled) {
    return (
      <div className="alert alert-info">
        <svg
          xmlns="http://www.w3.org/2000/svg"
          fill="none"
          viewBox="0 0 24 24"
          className="stroke-current shrink-0 w-6 h-6"
        >
          <path
            strokeLinecap="round"
            strokeLinejoin="round"
            strokeWidth="2"
            d="M13 16h-1v-4h-1m1-4h.01M21 12a9 9 0 11-18 0 9 9 0 0118 0z"
          ></path>
        </svg>
        <span>This group uses sequential payout order (first-come-first-served)</span>
      </div>
    );
  }

  return (
    <div className="card bg-gradient-to-br from-purple-50 to-blue-50 shadow-xl border-2 border-purple-200">
      <div className="card-body">
        <h3 className="card-title text-2xl flex items-center gap-2">
          <span className="text-3xl">🎲</span>
          Fair Random Order
          <div className="badge badge-success">VRF Verified</div>
        </h3>

        <p className="text-gray-700 mb-4">
          Payout order was randomly shuffled using Chainlink VRF for provable fairness. No one can predict or manipulate the order.
        </p>

        {/* VRF Status */}
        <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
          <div className="bg-white p-4 rounded-lg">
            <p className="text-sm text-gray-600 mb-1">VRF Request Status</p>
            <div className="flex items-center gap-2">
              {fulfilled ? (
                <>
                  <span className="text-green-600 text-2xl">✓</span>
                  <span className="font-semibold text-green-700">Fulfilled</span>
                </>
              ) : (
                <>
                  <span className="loading loading-spinner loading-sm"></span>
                  <span className="font-semibold text-orange-600">Pending</span>
                </>
              )}
            </div>
          </div>

          <div className="bg-white p-4 rounded-lg">
            <p className="text-sm text-gray-600 mb-1">Randomness Source</p>
            <div className="flex items-center gap-2">
              <span className="text-2xl">🔗</span>
              <span className="font-semibold">Chainlink VRF v2</span>
            </div>
          </div>
        </div>

        {/* Random Seed Display */}
        {randomSeed && (
          <div className="bg-white p-4 rounded-lg mb-4">
            <p className="text-sm text-gray-600 mb-2">Random Seed (Verifiable)</p>
            <div className="font-mono text-xs break-all bg-gray-100 p-2 rounded">
              {randomSeed.toString()}
            </div>
            <p className="text-xs text-gray-500 mt-2">
              This seed was generated by Chainlink VRF and is cryptographically verifiable on-chain
            </p>
          </div>
        )}

        {/* Request ID */}
        {requestId && (
          <div className="bg-white p-4 rounded-lg mb-4">
            <p className="text-sm text-gray-600 mb-2">VRF Request ID</p>
            <div className="font-mono text-xs break-all bg-gray-100 p-2 rounded">
              {requestId.toString()}
            </div>
          </div>
        )}

        {/* Shuffled Queue Preview */}
        {payoutQueue && payoutQueue.length > 0 && (
          <div className="bg-white p-4 rounded-lg">
            <p className="text-sm font-semibold mb-3">Randomized Payout Order</p>
            <div className="space-y-2 max-h-60 overflow-y-auto">
              {payoutQueue.map((address, index) => (
                <div
                  key={index}
                  className="flex items-center gap-3 p-2 bg-gray-50 rounded"
                >
                  <div className="badge badge-primary">#{index + 1}</div>
                  <span className="font-mono text-sm flex-1">
                    {address.slice(0, 6)}...{address.slice(-4)}
                  </span>
                  {index === 0 && (
                    <span className="badge badge-success badge-sm">Next Payout</span>
                  )}
                </div>
              ))}
            </div>
          </div>
        )}

        {/* Fairness Guarantee */}
        <div className="bg-purple-100 p-4 rounded-lg border border-purple-300">
          <p className="text-sm font-semibold mb-2 flex items-center gap-2">
            <span>🛡️</span>
            Fairness Guarantee
          </p>
          <ul className="text-sm space-y-1 text-gray-700">
            <li>✓ Randomness generated by decentralized oracle network</li>
            <li>✓ Cryptographically verifiable on-chain</li>
            <li>✓ Impossible to predict or manipulate</li>
            <li>✓ Audited by Chainlink security team</li>
          </ul>
        </div>

        {/* Learn More Link */}
        <div className="text-center mt-4">
          <a
            href="https://docs.chain.link/vrf/v2/introduction"
            target="_blank"
            rel="noopener noreferrer"
            className="btn btn-sm btn-outline btn-primary"
          >
            Learn About Chainlink VRF →
          </a>
        </div>
      </div>
    </div>
  );
}

/**
 * Compact VRF badge for group cards
 */
export function VRFBadge({ useVRF }: { useVRF: boolean }) {
  if (!useVRF) return null;

  return (
    <div className="tooltip tooltip-right" data-tip="Fair random payout order using Chainlink VRF">
      <div className="badge badge-success gap-1">
        <span>🎲</span>
        <span>Fair Random</span>
      </div>
    </div>
  );
}

/**
 * VRF request status indicator
 */
export function VRFStatusIndicator({ fulfilled, pending }: { fulfilled: boolean; pending: boolean }) {
  if (fulfilled) {
    return (
      <div className="flex items-center gap-2 text-green-600">
        <span className="text-xl">✓</span>
        <span className="font-semibold">VRF Fulfilled</span>
      </div>
    );
  }

  if (pending) {
    return (
      <div className="flex items-center gap-2 text-orange-600">
        <span className="loading loading-spinner loading-sm"></span>
        <span className="font-semibold">Awaiting VRF...</span>
      </div>
    );
  }

  return (
    <div className="flex items-center gap-2 text-gray-500">
      <span>🎲</span>
      <span>VRF Not Requested</span>
    </div>
  );
}
